### ISSUE TITLE
bug somewhere

### ISSUE THREAD

**Issue by roylus** [learn-co-students/for-loops-readme-data-science-intro-000#1]
I can't figure out what's wrong here but i don't think this example should be producing an index error. Also see Mexico City example - it should just be added to the end of the list, not listed repeatedly, right? 
<img width="863" alt="screen shot 2019-01-31 at 4 36 58 pm" src="https://user-images.githubusercontent.com/5768311/52087064-745aff00-2576-11e9-92b3-17c790474759.png">

**Comment by LoreDirick** [comment]
@cthauser thanks for raising!
the index was wrong
`i` in the for statement, yet `index` while iterating. Changed to `index` everywhere.
I fixed it!
